# Generated by Django 2.1.2 on 2018-10-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('NC', 'Not completed'), ('C', 'Completed')], default='NC', max_length=20),
        ),
    ]
